#!/bin/bash

checkstorage="$(df -h | grep root | awk '{print $5}' | tr -d '%')"
availstorage="$(df -h | grep root | awk '{print $4}' )"
usedstorage="$(df -h | grep root | awk '{print $3}' )"
fullstorage="$(df -h | grep root | awk '{print $2}' )"
namestorage="$(df -h | grep root | awk '{print $2}' )"
availpercent="$(expr 100 -  $(df -h | grep root | awk '{print $5}' | tr -d '%'))"

timestamp="$(date '+%Y-%m-%d %T')"

if [[ $checkstorage -gt "80" ]]; then
	/bin/echo "" > /var/log/daemon.log
	/bin/rm /var/log/daemon.log.*
	/bin/rm /var/log/daemon.log.*.*
	/bin/echo "" > /var/log/debug
	/bin/rm /var/log/debug.*
	/bin/rm /var/log/debug.*.*
	/bin/echo "" > /var/log/messages
	/bin/rm /var/log/messages.*
	/bin/rm /var/log/messages.*.*
	/bin/echo "" > /var/log/ppp-connect-errors
	/bin/rm /var/log/ppp-connect-errors.*
	/bin/rm /var/log/messages.*.*
	/bin/echo "" > /var/log/syslog
	/bin/rm /var/log/syslog.*
	/bin/rm /var/log/syslog.*.*

	echo "$timestamp - (ALERT!) Filesystem $namestorage yang digunakan $usedstorage dari $fullstorage [ $checkstorage% ]" >> /var/log/cleaning.log
	echo "(INFO) Beberapa file log backup akan dihapus" >> /var/log/cleaning.log
	echo "(INFO) Tapping akan direboot " >> /var/log/cleaning.log

	/sbin/reboot
else
	echo "$timestamp - (SAFE!) Filesystem $namestorage digunakan $usedstorage dari $fullstorage [ $checkstorage% ]" >> /var/log/cleaning.log
	echo "(INFO) Filesystem tersisa $availstorage dari $fullstorage [ $availpercent% ] " >> /var/log/cleaning.log 
fi
